import {pathToFileURL} from 'node:url';import {resolve} from 'node:path';import {spawn} from 'node:child_process';import {mkdir,writeFile} from 'node:fs/promises';import assert from 'node:assert/strict';import {build} from 'esbuild';
const {chromium}=await import(pathToFileURL(resolve(`${process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES}/playwright/index.mjs`)).href);
const server=spawn(process.execPath,['services/brain-gateway/src/server.ts'],{stdio:'ignore',env:{...process.env,SURVIVE_MODEL_API_KEY:'',SURVIVE_PORT:'8793'}});
const browser=await chromium.launch({executablePath:process.env.BROWSER_EXECUTABLE_PATH??'/workspace/scratch/4be8967a8182/browser-tools/runtime/chromium',headless:true,args:['--no-sandbox','--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader']});const profiles=[];
const fixture=Array.from({length:24},(_,i)=>({id:'fixture-'+i,runId:'explicit-archive-ui-fixture',tick:i*20,residentId:'resident-a',category:i%4===0?'decision':'action',text:i%4===0?'Mock UI fixture：计划建房，尚未执行。':`Mock UI fixture 实际记录${i}：取得1份木材。` }));fixture.push({...fixture[0],id:'other-private',residentId:'resident-b',text:'其他居民私人秘密_不得进入总结'});
try{
 for(let i=0;i<40;i++){try{if((await fetch('http://127.0.0.1:8793/api/health')).ok)break;}catch{}await new Promise(r=>setTimeout(r,100));}
 for(const size of [{width:1280,height:720,touch:false},{width:844,height:390,touch:true}]){
  const context=await browser.newContext({viewport:{width:size.width,height:size.height},hasTouch:size.touch});const page=await context.newPage();const errors=[];let requests=0,release,requestData;page.on('pageerror',e=>errors.push(e.message));
  await page.addInitScript(rows=>{if(!localStorage.getItem('survive_resident_history_v1'))localStorage.setItem('survive_resident_history_v1',JSON.stringify(rows));},fixture);
  await page.route('**/api/summarize',async route=>{requests++;requestData=route.request().postDataJSON();if(requests===1){await new Promise(r=>release=r);const first=requestData.entries.find(e=>e.category==='action'),plan=requestData.entries.find(e=>e.category==='decision');await route.fulfill({contentType:'application/json',body:JSON.stringify({requestId:requestData.requestId,runId:requestData.runId,residentId:requestData.residentId,source:'REAL_MODEL',model:'glm-4.5-air',fromTick:requestData.entries[0].tick,throughTick:requestData.entries.at(-1).tick,summary:{headline:'Mock UI 总结夹具',overview:'测试显示：有采集记录，建房仍是计划。',highlights:[{title:'测试关键进展',detail:'Mock UI：采集凭据可追溯。',kind:'progress',evidenceIds:[first.id]},{title:'建房未完成',detail:'仍是计划',kind:'plan',evidenceIds:[plan.id]}],nextFocus:[]}})});}else await route.fulfill({status:502,contentType:'application/json',body:JSON.stringify({message:'Mock网络失败，原始档案保留'})});});
  const texts=()=>page.evaluate(()=>{const walk=n=>n.visible===false?[]:[n,...(n._children??[]).flatMap(walk)];return walk(Laya.stage).filter(n=>typeof n.text==='string').map(n=>n.text);});
  const click=async(x,y)=>{const scale=Math.min(size.width/1280,size.height/720),px=(size.width-1280*scale)/2+x*scale,py=(size.height-720*scale)/2+y*scale;size.touch?await page.touchscreen.tap(px,py):await page.mouse.click(px,py);await page.waitForTimeout(120);};
  await page.goto('http://127.0.0.1:8793');await page.waitForFunction(()=>globalThis.Laya?.stage?._children?.some(n=>n.name==='Observer UI'));await click(78,555);
  assert.ok((await texts()).some(t=>t.includes('第1/4页')));await click(523,563);assert.ok((await texts()).some(t=>t.includes('第2/4页')));await click(403,563);assert.ok((await texts()).some(t=>t.includes('第1/4页')));
  await click(690,300);assert.ok((await texts()).some(t=>t.includes('详情 ·')));await click(660,560);
  await click(390,249);await click(1100,249);assert.ok((await texts()).some(t=>t.includes('还没有这一轮')));await click(814,561);await page.waitForFunction(()=>true);assert.equal(requests,1);assert.ok((await texts()).some(t=>t.includes('正在整理档案')));
  await click(499,249);await click(523,563);assert.ok((await texts()).some(t=>t.includes('实际记录')));assert.ok(!JSON.stringify(requestData).includes('其他居民私人秘密'));assert.equal(requestData.entries.length,24);release();await page.waitForFunction(()=>JSON.parse(localStorage.getItem('survive_archive_summaries_v1')||'[]').length===1);await click(390,249);
  await page.waitForFunction(()=>{const walk=n=>n.visible===false?[]:[n,...(n._children??[]).flatMap(walk)];return walk(Laya.stage).some(n=>typeof n.text==='string'&&n.text.includes('★ 关键进展'));},{},{timeout:8000}).catch(async e=>{console.log(JSON.stringify({viewport:size,texts:await texts()}));throw e;});await click(700,346);assert.ok((await texts()).some(t=>t.includes('原始记录依据')));assert.ok((await texts()).some(t=>t.includes('取得1份木材')));
  await mkdir('local-evidence',{recursive:true});await page.screenshot({path:`local-evidence/archive-summary-${size.width}.png`});await click(660,562);await click(814,561);await page.waitForFunction(()=>{const walk=n=>n.visible===false?[]:[n,...(n._children??[]).flatMap(walk)];return walk(Laya.stage).some(n=>typeof n.text==='string'&&n.text.includes('Mock网络失败'));});assert.ok((await texts()).some(t=>t.includes('Mock网络失败')));assert.equal(requests,2);
  await page.reload();await page.waitForFunction(()=>globalThis.Laya?.stage?._children?.some(n=>n.name==='Observer UI'));await click(78,555);await click(390,249);assert.ok((await texts()).some(t=>t.includes('Mock UI 总结夹具')));assert.equal(requests,2);assert.deepEqual(errors,[]);
  await page.evaluate(()=>localStorage.setItem('survive_resident_history_v1','[]'));await page.reload();await page.waitForFunction(()=>globalThis.Laya?.stage?._children?.some(n=>n.name==='Observer UI'));await click(78,555);await click(390,249);assert.ok((await texts()).some(t=>t.includes('Mock UI 总结夹具')));await click(700,346);assert.ok((await texts()).some(t=>t.includes('原始记录依据')));
  profiles.push({viewport:size,previousNextPages:true,oldRunsVisibleAfterReload:true,detailEvidence:true,summaryLoadingAndFailure:true,summaryPersisted:true,summaryEvidenceSurvivesRawArchiveEviction:true,isolatedResidentInput:true,transport:'explicit_mock_fixture_only',realModelCalls:0,errors});await context.close();
 }
 // Dynamic explicit UI fixture: incoming rows must not move the page currently being read.
 const bundled=await build({stdin:{resolveDir:process.cwd(),contents:`import {initialize} from './apps/laya-client/src/view.ts';import {createCampWorld} from './packages/sim-core/src/world.ts';const w=createCampWorld();const history=Array.from({length:20},(_,i)=>({id:'dynamic-'+i,runId:w.runId,residentId:'resident-a',tick:i,category:'action',text:'Mock动态记录'+i}));let version=1;globalThis.appendArchiveFixture=()=>{history.push({id:'new-'+version,runId:w.runId,residentId:'resident-a',tick:20+version,category:'action',text:'Mock新增记录'+version});version++;};const noop=()=>{};initialize({onTask:noop,onPause:noop,onResume:noop,onRetry:noop,onStop:noop,onSelect:noop,onToggleSenses:noop,onReplay:noop,onLive:noop,onSeek:noop,onSpeed:noop,onStart:noop,onConnect:noop}).then(view=>Laya.timer.frameLoop(1,null,()=>view.render({world:w,overlays:{},selectedId:'resident-a',showSenses:false,speed:1,hosted:true,playbackTick:0,maxTick:0,mode:'REAL_MODEL',status:'PAUSED',history,historyVersion:version})));`,sourcefile:'explicit-archive-ui-fixture.ts'},bundle:true,write:false,format:'iife',platform:'browser',target:'es2022'});
 const page=await browser.newPage({viewport:{width:1280,height:720}});await page.route('**/app.js',r=>r.fulfill({contentType:'application/javascript',body:bundled.outputFiles[0].text}));await page.goto('http://127.0.0.1:8793');await page.waitForFunction(()=>globalThis.appendArchiveFixture&&Laya.stage?._children?.some(n=>n.name==='Observer UI'));await page.mouse.click(78,555);await page.waitForTimeout(120);await page.mouse.click(523,563);await page.waitForTimeout(120);
 const visible=()=>page.evaluate(()=>{const walk=n=>n.visible===false?[]:[n,...(n._children??[]).flatMap(walk)];return walk(Laya.stage).filter(n=>typeof n.text==='string'&&n.text.startsWith('Mock动态记录')).map(n=>n.text);});const before=await visible();assert.equal(before.length,5);await page.evaluate(()=>{for(let i=0;i<30;i++)appendArchiveFixture();});await page.waitForTimeout(150);assert.deepEqual(await visible(),before);await page.mouse.click(980,561);await page.waitForTimeout(150);assert.equal((await visible()).length,0);await page.close();
 await writeFile('evidence/archive-browser.json',JSON.stringify({status:'passed',profiles,dynamicPaginationStable:true,physicalDevice:'not_run',liveModelBrowser:'not_run',modelResponseFixture:'explicit_mock_transport_source_field_exercises_validation_not_real_model'},null,2)+'\n');console.log(JSON.stringify({status:'passed',profiles:profiles.length,dynamicPaginationStable:true}));
}finally{await browser.close();server.kill();}
