import {pathToFileURL} from 'node:url';import {resolve} from 'node:path';import {spawn} from 'node:child_process';import {mkdir,writeFile,readFile} from 'node:fs/promises';import {build} from 'esbuild';import assert from 'node:assert/strict';
const {chromium}=await import(pathToFileURL(resolve(`${process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES}/playwright/index.mjs`)).href);
const server=spawn(process.execPath,['services/brain-gateway/src/server.ts'],{stdio:'ignore',env:{...process.env,SURVIVE_MODEL_API_KEY:'',SURVIVE_PORT:'8796'}});const browser=await chromium.launch({executablePath:process.env.BROWSER_EXECUTABLE_PATH??'/workspace/scratch/4be8967a8182/browser-tools/runtime/chromium-restored',headless:true,args:['--no-sandbox','--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader']});const results=[];
try{
 const out=await build({stdin:{resolveDir:process.cwd(),sourcefile:'art-fixture.ts',contents:`import {initialize} from './apps/laya-client/src/view.ts';import {createCrewWorld} from './packages/sim-core/src/world.ts';import {postTask} from './packages/sim-core/src/camp.ts';import {samplePerception,getOverlay} from './packages/sim-core/src/perception.ts';import {hashCanonical} from './packages/contracts/src/canonical.ts';
 const w=createCrewWorld(4);postTask(w,{kind:'house',siteId:'east',resource:'wood',amount:3,note:'场景美术夹具'});const h=w.objects.find(o=>o.kind==='plot');h.kind='house';h.buildStage=3;w.residents.forEach((r,i)=>{r.position={x:-2+i*1.6,y:0,z:2};r.heading=Math.PI/2;});samplePerception(w);let selected='resident-a';let senses=false;const noop=()=>{};globalThis.artHash=()=>hashCanonical(w);
 initialize({onTask:noop,onPause:noop,onResume:noop,onRetry:noop,onStop:noop,onSelect:id=>selected=id,onToggleSenses:()=>senses=!senses,onReplay:noop,onLive:noop,onSeek:noop,onSpeed:noop,onStart:noop,onConnect:noop}).then(view=>Laya.timer.frameLoop(1,null,()=>view.render({world:w,overlays:Object.fromEntries(w.residents.map(r=>[r.id,getOverlay(w,r)])),selectedId:selected,showSenses:senses,speed:1,hosted:true,playbackTick:0,maxTick:0,mode:'REPLAY',status:'PAUSED'})));`},bundle:true,write:false,format:'iife',target:'es2022',platform:'browser'});const app=out.outputFiles[0].text;
 for(let i=0;i<40;i++){try{if((await fetch('http://127.0.0.1:8796/api/health')).ok)break;}catch{}await new Promise(r=>setTimeout(r,100));}
 const fontRoot=resolve('../../browser-tools/node_modules/@fontsource-variable/noto-sans-sc');const css=(await readFile(resolve(fontRoot,'index.css'),'utf8')).replaceAll('Noto Sans SC Variable','Noto Sans CJK SC').replaceAll('./files/','/_qa_fonts/');const chars=[...new Set(app.replace(/\\u([0-9a-f]{4})/gi,(_,code)=>String.fromCharCode(parseInt(code,16))).match(/[\u3400-\u9fff]/g))].join('');
 for(const profile of [{width:1440,height:900,dpr:1},{width:844,height:390,dpr:2}]){
  const p=await browser.newPage({viewport:{width:profile.width,height:profile.height},deviceScaleFactor:profile.dpr,hasTouch:profile.dpr>1});const errors=[];p.on('pageerror',e=>errors.push(e.message));let calls=0;p.on('request',r=>{if(/\/api\/(decide|command|summarize)/.test(r.url()))calls++;});
  await p.route('**/_qa_fonts/*',async r=>r.fulfill({contentType:'font/woff2',body:await readFile(resolve(fontRoot,'files',r.request().url().split('/').at(-1)))}));
  await p.route('**/app.js',r=>r.fulfill({contentType:'application/javascript',body:'(async()=>{const s=document.createElement("style");s.textContent='+JSON.stringify(css)+';document.head.appendChild(s);await document.fonts.load('+JSON.stringify('14px Noto Sans CJK SC')+','+JSON.stringify(chars)+');\n'+app+'\n})();'}));await p.goto('http://127.0.0.1:8796');await p.waitForFunction(()=>typeof globalThis.artHash==='function'&&Laya.stage?._children.some(n=>n.name==='Observer UI'));await p.waitForTimeout(1800);
  const before=await p.evaluate(()=>artHash());await mkdir('local-evidence',{recursive:true});await p.screenshot({path:`local-evidence/art-${process.env.ART_LABEL??'after'}-${profile.width}.png`});
  const size=await p.evaluate(()=>{const c=document.querySelector('canvas'),b=c.getBoundingClientRect();return {pixels:[c.width,c.height],css:[b.width,b.height],retina:Laya.Config.useRetinalCanvas};});
  const scale=Math.min(profile.width/1280,profile.height/720),click=async(x,y)=>{await p.mouse.click((profile.width-1280*scale)/2+x*scale,(profile.height-720*scale)/2+y*scale);await p.waitForTimeout(350);};await click(210,552);await click(143,595);await p.waitForTimeout(350);assert.equal(await p.evaluate(()=>artHash()),before);assert.equal(calls,0);assert.deepEqual(errors,[]);
  results.push({profile,canvas:size,worldUnchanged:true,modelCalls:calls,errors});await p.close();
 }
 await writeFile(`evidence/art-${process.env.ART_LABEL??'after'}-browser.json`,JSON.stringify({status:'passed',mode:'EXPLICIT_RENDER_FIXTURE',results,physicalDevice:'not_run',realModel:'not_run_visual_only'},null,2)+'\n');console.log(JSON.stringify(results));
}finally{await browser.close();server.kill();}
