/** Official real provider + previously captured real replay. Only aggregate evidence is publishable. */
import {readFile,writeFile,mkdir} from 'node:fs/promises';
import {JournalSummaryGateway} from '../services/brain-gateway/src/summary.ts';import {loadConfig} from '../services/brain-gateway/src/gateway.ts';
import {ResidentJournal} from '../apps/laya-client/src/journal.ts';import {summaryInput} from '../apps/laya-client/src/journal-summary.ts';
import {hashCanonical} from '../packages/contracts/src/canonical.ts';import {buildContext} from '../packages/sim-core/src/perception.ts';
console.log('Ready for real summary credential on stdin');let input='';for await(const chunk of process.stdin){input+=chunk;if(input.includes('\n'))break;}const apiKey=JSON.parse(input).apiKey;input='';
const replay=JSON.parse(await readFile('evidence/real-meeting-replay.json','utf8'));if(replay.manifest.decisionMode!=='real')throw Error('Expected authentic real-model recording');
const journal=new ResidentJournal();for(const frame of replay.frames)journal.collect(frame.world);const world=replay.frames.at(-1).world,before=hashCanonical(world);const contexts=world.residents.map((r:any)=>hashCanonical(buildContext(world,r)));
const gateway=new JournalSummaryGateway(loadConfig({SURVIVE_MODEL_API_KEY:apiKey}));const results=[];await mkdir('local-evidence',{recursive:true});
for(const r of world.residents){const request=summaryInput(journal.rows,r.id,r.name,world.runId,false)!;const start=Date.now();const response=await gateway.summarize(request);await writeFile(`local-evidence/summary-${r.id}.json`,JSON.stringify({request,response},null,2));results.push({residentId:r.id,inputEntries:request.entries.length,fromTick:response.fromTick,throughTick:response.throughTick,highlights:response.summary.highlights.length,kinds:response.summary.highlights.map(p=>p.kind),citedEvidenceValidated:true,durationMs:Date.now()-start});console.log(JSON.stringify(results.at(-1)));}
const unchanged=hashCanonical(world)===before&&world.residents.every((r:any,i:number)=>hashCanonical(buildContext(world,r))===contexts[i]);if(!unchanged)throw Error('Observer summary mutated resident context');
const report={status:'passed',checkedAt:new Date().toISOString(),execution:'node_local_official_provider_on_authentic_prior_real_replay',source:'REAL_MODEL',model:'glm-4.5-air',mockUsed:false,residents:results,worldAndResidentContextsUnchanged:unchanged,scope:'Historical two-resident encounter only; not a new autonomous construction run or live browser model test',liveModelBrowser:'not_run',physicalDevice:'not_run'};
await writeFile('evidence/archive-real.json',JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify({status:'passed',residents:results.length,worldAndResidentContextsUnchanged:unchanged}));
